sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - npm run test:once
after_success:
  - npm run coverage
  - npm run report-coverage
  - npm run semantic-release
